# Generated by Django 3.2 on 2021-09-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('SW', 'SmartWatch'), ('P', 'Phone'), ('Pl', 'Planshet')], max_length=2)),
                ('price', models.FloatField()),
                ('condition', models.CharField(max_length=50)),
                ('label', models.CharField(choices=[('Y', 'primary'), ('D', 'danger'), ('S', 'secondry')], max_length=2)),
            ],
        ),
    ]
